// todo- delete types AI MANUAL
export enum TCreationModeButton {
  AI = "AI",
  MANUAL = "MANUAL",
  AI_QUESTIONS = "AI_QUESTIONS",
  MANUAL_QUESTIONS = "MANUAL_QUESTIONS",
  AI_THEMES = "AI_THEMES",
  MANUAL_THEMES = "MANUAL_THEMES",
}
