name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group:'pages'
  cancel-in-progress: true

jobs:
  deploy:
     enviroment:
        name:gihub-pages
        url:${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
  
      strategy:
        matrix:
          node-version: [18.x, 20.x, 22.x]
  
      steps:
      - uses: actions/checkout@v4
  
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm
      - name: Install depencies
              run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
              uses: actions/configure-pages@v3
      - name: Upload artifact
              uses: actions/upload-pages-artifact@v2
              with: path: './build'
      - name: Deploy to GiHub Pages
              id: deployment
              uses: actions/deploy-pages@v2
 
        
  
